#!/bin/bash

DEFAULTCONFIG=$(cat <<EOF
40:1
50:2
60:2
75:3
85:4
92:full-speed
EOF
)
AUTOFANVAL="1"

setAuto() {
    while true; do
        temperature=$(awk '{print $2}' /proc/acpi/ibm/thermal)
        echo "First temperature value: $temperature"
        while IFS=":" read -r key value; do
            if [ "$temperature" -ge "$key" ]; then
                AUTOFANVAL="$value"
                echo "set fan speed to $value"
            fi
        done < /etc/E16FanControlConfig.txt
        echo "level $AUTOFANVAL" | sudo tee /proc/acpi/ibm/fan > /dev/null

        sleep 20
    done
}

if [ "$1" == "-setSpeed" ]; then
    if [[ "$2" =~ ^[0-9]+$ ]]; then
        if [ "$2" -lt 1 ] || [ "$2" -gt 7 ]; then
            echo "Invalid Argument: Speed must be between 1-7."

        else
            sudo systemctl stop e16-fancontrol.service
            echo "level $2" | sudo tee /proc/acpi/ibm/fan > /dev/null
            echo "Speed set to $2"

        fi
    elif [ "$2" == "max" ]; then
        sudo systemctl stop e16-fancontrol.service

        echo "level full-speed" | sudo tee /proc/acpi/ibm/fan > /dev/null
        echo "Setting speed to maximum."
    elif [ "$2" == "auto" ]; then
        echo "Setting to auto mode"
        if [ ! -e /etc/E16FanControlConfig.txt ]; then
            echo "$DEFAULTCONFIG" > /etc/E16FanControlConfig.txt
            echo "Default configuration created at /etc/E16FanControlConfig.txt"
        fi
        if systemctl list-unit-files | grep -q "e16-fancontrol.service";then
            echo "Found systemd Service"
            systemctl daemon-reload
            sudo systemctl restart e16-fancontrol.service
            systemctl enable e16-fancontrol.service 
        else
            echo "Could not find systemd service please execute ./setup"
        fi
    else
        echo "Invalid Argument: Speed must be a number between 1-7, max, or auto."
    fi

elif [ "$1" == "-autoSet" ]; then
    setAuto
else
    echo "
Available Commands:
    -setSpeed <value>: Set fan speed (1-7),max or auto

    Created By Haisen V Kandy
    "
fi
